apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bakerydemo
spec:
  # Attempt to keep a single instance of this Pod running at all times
  replicas: 1
  template:
    # This is the Pod definition!
    metadata:
      labels:
        app: bakerydemo
    spec:
      containers:
      - name: bakerydemo
        # The user, repository, and tag of the image we're deploying
        image: wagtail/bakerydemo:gcloud
        imagePullPolicy: Always
        # On which port(s) does this container listen?
        ports:
        - containerPort: 8000
        # Kubernetes boilerplate (how to lookup Pod hostnames):
        env:
        - name: GET_HOSTS_FROM
          value: dns
